- hosts: all
  name: Autoconverted job legacy-tempest-dsvm-patrole-multinode-member from old job
    gate-tempest-dsvm-patrole-multinode-member-ubuntu-xenial-nv
  tasks:

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack-infra/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              git://git.openstack.org \
              openstack-infra/devstack-gate
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          cat << 'EOF' >>"/tmp/dg-local.conf"
          [[local|localrc]]
          enable_plugin patrole git://git.openstack.org/openstack/patrole
          TEMPEST_PLUGINS='/opt/stack/new/patrole'
          # Needed by Patrole devstack plugin
          RBAC_TEST_ROLE=member

          EOF
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export PYTHONUNBUFFERED=true

          # Ensure that tempest set up is executed, but do not automatically
          # execute tempest tests; they are executed in post_test_hook.
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_TOPOLOGY="multinode"
          export DEVSTACK_GATE_TEMPEST_REGEX='(?=.*\[.*\bslow\b.*\])(^patrole_tempest_plugin\.tests\.api)'
          export DEVSTACK_GATE_TEMPEST_ALL_PLUGINS=1

          export PROJECTS="openstack/patrole $PROJECTS"

          export BRANCH_OVERRIDE=default
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'
