- hosts: all
  name: Autoconverted job legacy-zun-devstack-dsvm-docker-etcd from old job gate-zun-devstack-dsvm-docker-etcd-nv
  tasks:

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack-infra/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              git://git.openstack.org \
              openstack-infra/devstack-gate
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          cat << 'EOF' >>"/tmp/dg-local.conf"
          [[local|localrc]]
          enable_plugin zun git://git.openstack.org/openstack/zun

          EOF
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x

          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=0
          export DEVSTACK_GATE_NEUTRON=1

          # Enable tempest for tempest plugin
          export ENABLED_SERVICES=tempest

          export PROJECTS="openstack/zun $PROJECTS"
          export PROJECTS="openstack/kuryr-libnetwork $PROJECTS"
          export PROJECTS="openstack/python-zunclient $PROJECTS"
          export PROJECTS="openstack/devstack-plugin-container $PROJECTS"

          # Keep localrc to be able to set some vars in post_test_hook
          export KEEP_LOCALRC=1

          function gate_hook {
               cd /opt/stack/new/zun/
              ./zun/tests/contrib/gate_hook.sh docker etcd
          }
          export -f gate_hook

          function post_test_hook {
              source $BASE/new/devstack/accrc/admin/admin
              cd /opt/stack/new/zun/
              ./zun/tests/contrib/post_test_hook.sh docker
          }
          export -f post_test_hook

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'
