- hosts: all
  name: Autoconverted job legacy-group-based-policy-dsvm-rally-ubuntu-trusty from
    old job gate-group-based-policy-dsvm-rally-ubuntu-trusty-nv
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              https://opendev.org \
              openstack/devstack-gate
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_UNSTACK=1
          export DEVSTACK_GATE_TEMPEST=0
          export DEVSTACK_GATE_EXERCISES=0
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_INSTALL_TESTONLY=1
          export PROJECTS="x/group-based-policy $PROJECTS"
          export PROJECTS="x/group-based-policy-automation $PROJECTS"
          export PROJECTS="x/group-based-policy-ui $PROJECTS"
          export PROJECTS="x/python-group-based-policy-client $PROJECTS"
          export BRANCH_OVERRIDE=default
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi

          function gate_hook {
              bash -xe $BASE/new/group-based-policy/gbpservice/tests/contrib/gate_hook.sh dsvm-rally
          }
          export -f gate_hook

          function post_test_hook {
             bash -xe $BASE/new/group-based-policy/gbpservice/tests/contrib/post_test_rally_hook.sh dsvm-rally
          }
          export -f post_test_hook

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
